---
apiVersion: contour.heptio.com/v1beta1
kind: IngressRoute
metadata: 
  name: health-check
  namespace: default
spec: 
  virtualhost:
    fqdn: health.bar.com
  routes: 
    - match: /
      services: 
        - name: s1-def-health
          port: 80
        - name: s2-def-health
          port: 80